export const INITIAL_USER_LOCATION = {
  lat: 28.6215,
  lng: 77.3640,
  address: "JSS Academy of Technical Education Campus, Noida"
};

export const WASTE_CATEGORIES = [
  { id: 'all', label: 'All Bins', icon: 'Trash2', color: 'bg-gray-100 text-gray-700' },
  { id: 'general', label: 'General Waste', icon: 'Trash2', color: 'bg-slate-100 text-slate-800' },
  { id: 'recyclable', label: 'Plastic & Recyclable', icon: 'Recycle', color: 'bg-blue-50 text-blue-700' },
  { id: 'organic', label: 'Organic / Wet Waste', icon: 'Leaf', color: 'bg-emerald-50 text-emerald-700' },
  { id: 'glass', label: 'Glass & Metals', icon: 'Wine', color: 'bg-purple-50 text-purple-700' },
  { id: 'ewaste', label: 'E-Waste Hub', icon: 'Zap', color: 'bg-amber-50 text-amber-700' },
];

export const MOCK_BINS = [
  // --- JSS UNIVERSITY CAMPUS DUSTBINS ---
  {
    id: "BIN-JSS-01",
    name: "JSS Main Gate 1 Smart Bin",
    lat: 28.6215,
    lng: 77.3640,
    address: "JSSATE Main Entrance Gate 1, Campus Road",
    area: "JSS University Campus",
    category: "recyclable",
    wasteType: "Plastic & Beverage Cans",
    fillLevel: 38,
    capacityLiters: 200,
    lastCollected: "2 hours ago",
    suitableItems: ["PET Water Bottles", "Aluminium Cans", "Cardboard Folders"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-JSS-02",
    name: "JSS Central Canteen Courtyard",
    lat: 28.6218,
    lng: 77.3645,
    address: "Canteen Plaza, JSSATE Campus",
    area: "JSS University Campus",
    category: "organic",
    wasteType: "Organic & Food Waste",
    fillLevel: 85,
    capacityLiters: 240,
    lastCollected: "14 hours ago",
    suitableItems: ["Leftover Canteen Food", "Fruit Peels", "Biodegradable Plates", "Tea Cups"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-JSS-03",
    name: "JSS Academic Block 1 (CS/IT)",
    lat: 28.6222,
    lng: 77.3638,
    address: "Computer Science Dept Entrance, JSSATE",
    area: "JSS University Campus",
    category: "recyclable",
    wasteType: "Paper & Plastic Stream",
    fillLevel: 42,
    capacityLiters: 180,
    lastCollected: "3 hours ago",
    suitableItems: ["Assignment Sheets", "Plastic Wrappers", "Cold Drink Cans"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-JSS-04",
    name: "JSS Mechanical Block Annex",
    lat: 28.6210,
    lng: 77.3632,
    address: "Mechanical & Civil Workshop Wing, JSSATE",
    area: "JSS University Campus",
    category: "general",
    wasteType: "General Waste",
    fillLevel: 64,
    capacityLiters: 220,
    lastCollected: "6 hours ago",
    suitableItems: ["Workshop Scrap", "General Packaging", "Paper Wipes"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-JSS-05",
    name: "JSS Central Library & Lawn",
    lat: 28.6225,
    lng: 77.3648,
    address: "Central Library Quadrangle, JSSATE",
    area: "JSS University Campus",
    category: "recyclable",
    wasteType: "Plastic & Beverage Bottles",
    fillLevel: 28,
    capacityLiters: 160,
    lastCollected: "1 hour ago",
    suitableItems: ["Juice Cartons", "Water Bottles", "Snack Packets"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-JSS-06",
    name: "JSS Boys Hostel Gate 1",
    lat: 28.6205,
    lng: 77.3652,
    address: "Boys Hostel Road, JSSATE Campus",
    area: "JSS University Campus",
    category: "organic",
    wasteType: "Food Scraps & Biodegradables",
    fillLevel: 91,
    capacityLiters: 250,
    lastCollected: "16 hours ago",
    suitableItems: ["Mess Leftovers", "Fruit Waste", "Organic Packaging"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-JSS-07",
    name: "JSS Girls Hostel Lawn",
    lat: 28.6230,
    lng: 77.3655,
    address: "Girls Hostel Residence Block, JSSATE",
    area: "JSS University Campus",
    category: "recyclable",
    wasteType: "Plastics & Paper",
    fillLevel: 55,
    capacityLiters: 180,
    lastCollected: "5 hours ago",
    suitableItems: ["Cosmetic Containers", "Plastic Bottles", "Cardboard boxes"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-JSS-08",
    name: "JSS Incubation Center (TBI)",
    lat: 28.6212,
    lng: 77.3646,
    address: "Technology Business Incubator, JSSATE",
    area: "JSS University Campus",
    category: "ewaste",
    wasteType: "Electronic Waste Drop",
    fillLevel: 30,
    capacityLiters: 120,
    lastCollected: "1 day ago",
    suitableItems: ["Old USB Cables", "Dead Batteries", "Broken PC Peripherals"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-JSS-09",
    name: "JSS Sports Ground & Gym",
    lat: 28.6202,
    lng: 77.3638,
    address: "Sports Complex Pavilion, JSSATE",
    area: "JSS University Campus",
    category: "general",
    wasteType: "General Waste",
    fillLevel: 76,
    capacityLiters: 200,
    lastCollected: "8 hours ago",
    suitableItems: ["Energy Drink Cans", "Sports Tape", "General Litter"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-JSS-10",
    name: "JSS Campus Back Gate 2",
    lat: 28.6228,
    lng: 77.3632,
    address: "Gate 2 Exit, C-Block Road, JSSATE",
    area: "JSS University Campus",
    category: "glass",
    wasteType: "Glass & Metals",
    fillLevel: 48,
    capacityLiters: 150,
    lastCollected: "4 hours ago",
    suitableItems: ["Glass Bottles", "Metal Cans", "Jar Containers"],
    sensorStatus: "Online",
  },

  // --- SURROUNDING SECTOR DUSTBINS ---
  {
    id: "BIN-ND62-01",
    name: "Fortis Hospital Gate 1 Bin",
    lat: 28.6265,
    lng: 77.3680,
    address: "B-22, Opposite Fortis Hospital Entrance",
    area: "Institutional Zone",
    category: "general",
    wasteType: "General Waste",
    fillLevel: 45,
    capacityLiters: 240,
    lastCollected: "2 hours ago",
    suitableItems: ["Non-hazardous wrappers", "Paper tissues", "General litter"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-ND62-02",
    name: "Electronic City Metro Gate 1",
    lat: 28.6272,
    lng: 77.3712,
    address: "Noida Electronic City Metro Station",
    area: "Transit Circle",
    category: "recyclable",
    wasteType: "Plastic & Metal Cans",
    fillLevel: 88,
    capacityLiters: 300,
    lastCollected: "14 hours ago",
    suitableItems: ["Aluminium Beverage Cans", "PET Water Bottles", "Juice Cartons"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-ND62-03",
    name: "The Corenthum Tower B Recycler",
    lat: 28.6290,
    lng: 77.3660,
    address: "A-41, Near Electronic City Metro",
    area: "Commercial Hub",
    category: "recyclable",
    wasteType: "Paper & Cardboard",
    fillLevel: 35,
    capacityLiters: 200,
    lastCollected: "1 hour ago",
    suitableItems: ["Office Paper", "Cardboard boxes", "Soda Cans"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-ND62-04",
    name: "Tot Mall Market Courtyard",
    lat: 28.6240,
    lng: 77.3630,
    address: "Tot Mall Complex Courtyard",
    area: "Commercial Market",
    category: "organic",
    wasteType: "Biodegradable Food Waste",
    fillLevel: 92,
    capacityLiters: 250,
    lastCollected: "18 hours ago",
    suitableItems: ["Food Stall Waste", "Vegetable Scraps", "Wet Waste"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-ND62-05",
    name: "C-DAC Innovation Park E-Waste",
    lat: 28.6255,
    lng: 77.3590,
    address: "Anusandhan Bhawan, C-56/1 Complex",
    area: "R&D Zone",
    category: "ewaste",
    wasteType: "Electronic Waste",
    fillLevel: 28,
    capacityLiters: 150,
    lastCollected: "1 day ago",
    suitableItems: ["Computer Cables", "Mobile Batteries", "Circuit Boards"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-ND62-06",
    name: "Stellar IT Park Glass & Metal Bin",
    lat: 28.6225,
    lng: 77.3575,
    address: "C-25, Stellar IT Park Entrance",
    area: "Tech Park Zone",
    category: "glass",
    wasteType: "Glass & Jars",
    fillLevel: 76,
    capacityLiters: 160,
    lastCollected: "6 hours ago",
    suitableItems: ["Glass Drink Bottles", "Jam Jars", "Metal Containers"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-ND62-07",
    name: "IIM Noida Campus Gate Bin",
    lat: 28.6298,
    lng: 77.3620,
    address: "B-1, Institutional Area Road",
    area: "Institutional Zone",
    category: "recyclable",
    wasteType: "Dry Recyclable Waste",
    fillLevel: 50,
    capacityLiters: 180,
    lastCollected: "5 hours ago",
    suitableItems: ["Plastic Bottles", "Notebook Paper", "Aluminium Cans"],
    sensorStatus: "Online",
  },
  {
    id: "BIN-ND62-08",
    name: "Logix Cyber Park Tower C",
    lat: 28.6185,
    lng: 77.3605,
    address: "C-28/29, Cyber Park Gate",
    area: "Cyber District",
    category: "recyclable",
    wasteType: "Plastic & Beverage Cans",
    fillLevel: 40,
    capacityLiters: 220,
    lastCollected: "3 hours ago",
    suitableItems: ["Cold Drink Cans", "Plastic Water Bottles", "Cardboard Containers"],
    sensorStatus: "Online",
  }
];
